### ISSUE TITLE
Please migrate, and update audio recorder plugin

### ISSUE THREAD

**Issue by shinewanna** [anokabb/chat_composer#1]
Running "flutter pub get" in zay...                                17.0s
The plugin `flutter_audio_recorder2` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by shelzTimesignature** [comment]
hi do you have any plans of updating this package

**Comment by anokabb** [comment]
hello, I updated the package you can check the latest version, Thanks!

**Comment by shinewanna** [comment]
After upgrade to the latest version, can't build the project

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeLibDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Learn how to resolve the issue at [https://developer.android.com/studio/build/dependencies#duplicate_classes]().
           Type com.dooboolab.fluttersound.BuildConfig is defined multiple times: [/Users/shinewanna/app/zay/build/flutter_sound/.transforms/7075e9562b97a2ca94dab9aca70c4cf2/transformed/classes/classes.dex](), [/Users/shinewanna/app/zay/build/flutter_sound_lite/.transforms/6f06aeb2095eb4fedbc05233440f1cba/transformed/classes/classes.dex]()

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 33s
[!] App requires Multidex support
    Flutter multidex handling is disabled. If you wish to let the tool configure multidex, use the --mutidex flag.`

I already enabled multidex, this is something wrong.

`chat_composer: 1.0.1
flutter_sound: 8.5.0`
